module.exports = {
  REQUEST_PROJECT: 'REQUEST_PROJECT',
  SAVE_FILE: 'SAVE_FILE',
  SET_DOCUMENT: 'SET_DOCUMENT',
  CREATE_DOCUMENT: 'CREATE_DOCUMENT',
  REQUEST_SAVE_STATE: 'REQUEST_SAVE_STATE',
  CHECK_SAVED: 'CHECK_SAVED',
  REQUEST_SAVE: 'REQUEST_SAVE',
};
